apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-1
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project-1
  template:
    metadata:
      labels:
        app: project-1
    spec:
      containers:
      - name: project-1
        image: sachinthokal/project-1:latest
        ports:
        - containerPort: 80
