apiVersion: v1
kind: Service
metadata:
  name: project-1-service
spec:
  selector:
    app: project-1   # This selector matches the pods with the label "app=my-app"
  ports:
    - protocol: TCP
      port: 80         # The port the service is exposed on inside the cluster
      targetPort: 8080 # The port the application is running on inside the pod
  type: LoadBalancer        # Specifies that this is a NodePort service
